plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'dev.daniell.indigo.modules.biometrics'
version = '0.1.0'

android {
  namespace "dev.daniell.indigo.modules.biometrics"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation 'androidx.biometric:biometric:1.1.0'
}
